[package]
name = "sentry"
version = "0.1.0"
authors = ["David Rajchenbach-Teller <dteller@mozilla.com>"]
license = "MPL2"

[dependencies]
foxbox_taxonomy = { path = "../taxonomy/" }
gstreamer = "0.6.2"
lazy_static = "^0.1"
log = "0.3"
rand = "0.3"
